# Generated by Django 5.2.4 on 2025-07-06 14:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=255)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name_kana", models.CharField(blank=True, max_length=100)),
                ("first_name_kana", models.CharField(blank=True, max_length=100)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "男性"),
                            ("female", "女性"),
                            ("other", "その他"),
                            ("none", "無回答"),
                        ],
                        max_length=10,
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("instagram_id", models.CharField(blank=True, max_length=100)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("notes", models.TextField(blank=True)),
                ("skin_type", models.CharField(blank=True, max_length=100)),
                ("tattoo_experience", models.BooleanField(default=False)),
                ("occupation", models.CharField(blank=True, max_length=100)),
                ("referrer", models.CharField(blank=True, max_length=100)),
                ("mbti", models.CharField(blank=True, max_length=4)),
                ("tattooist", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TattooArtist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("last_name", models.CharField(blank=True, max_length=50)),
                ("first_name", models.CharField(blank=True, max_length=50)),
                ("artist_name", models.CharField(max_length=100)),
                ("furigana_name", models.CharField(blank=True, max_length=100)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "男性"),
                            ("female", "女性"),
                            ("other", "その他"),
                            ("none", "無回答"),
                        ],
                        max_length=10,
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("studio_name", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("prefecture", models.CharField(blank=True, max_length=100)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("google_maps_url", models.URLField(blank=True)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("instagram_url", models.URLField(blank=True)),
                ("line_url", models.URLField(blank=True)),
                ("tiktok_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("x_url", models.URLField(blank=True)),
                ("website_url", models.URLField(blank=True)),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="artist_profiles/"
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                ("specialties", models.CharField(blank=True, max_length=255)),
                ("is_public", models.BooleanField(default=True)),
                ("accepting_clients", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("consent_version", models.CharField(max_length=20)),
                ("signed_at", models.DateTimeField()),
                ("signature", models.TextField(blank=True, null=True)),
                ("privacy_policy_version", models.CharField(blank=True, max_length=20)),
                (
                    "privacy_policy_agreed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to="eform_api.customer",
                    ),
                ),
            ],
            options={
                "unique_together": {("customer", "consent_version")},
            },
        ),
    ]
