# Generated by Django 5.2.4 on 2025-07-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eform_api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="address",
        ),
        migrations.AddField(
            model_name="customer",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customer",
            name="prefecture",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
