# Generated by Django 5.2.4 on 2025-07-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eform_api", "0002_remove_customer_address_customer_city_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customerconsent",
            options={"ordering": ["-signed_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="customerconsent",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="customerconsent",
            name="visit_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
