# Generated by Django 5.2.4 on 2025-07-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eform_api", "0003_alter_customerconsent_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="avatar",
        ),
        migrations.RemoveField(
            model_name="tattooartist",
            name="profile_image",
        ),
        migrations.AddField(
            model_name="customer",
            name="avatar_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="tattooartist",
            name="profile_image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
