# Generated by Django 5.2.4 on 2025-07-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eform_api", "0004_remove_customer_avatar_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customerconsent",
            old_name="privacy_policy_agreed_at",
            new_name="privacy_agreement_agreed_at",
        ),
        migrations.RenameField(
            model_name="customerconsent",
            old_name="privacy_policy_version",
            new_name="privacy_agreement_version",
        ),
        migrations.AlterField(
            model_name="customer",
            name="birth_date",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
