# Generated by Django 5.2.4 on 2025-07-28 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "eform_api",
            "0005_rename_privacy_policy_agreed_at_customerconsent_privacy_agreement_agreed_at_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("terms_version", models.CharField(max_length=50)),
                ("terms_agreed_at", models.DateTimeField()),
                ("privacy_version", models.CharField(max_length=50)),
                ("privacy_agreed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreement",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
