# Generated by Django 4.2.25 on 2025-12-07 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eform_api', '0008_consententrytoken_consentaccesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='merged_into',
            field=models.ForeignKey(blank=True, help_text='この顧客が他の顧客にマージされた場合、その先', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='eform_api.customer'),
        ),
        migrations.AddField(
            model_name='customerconsent',
            name='customer_birth_date_snapshot',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customerconsent',
            name='customer_name_snapshot',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customerconsent',
            name='customer_phone_snapshot',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerconsent',
            name='customer_uuid_snapshot',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
